# Generated by Django 3.0.2 on 2020-08-02 03:01

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('realName', models.CharField(max_length=100)),
                ('tz', timezone_field.fields.TimeZoneField()),
                ('activityPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ActivityPeriod')),
            ],
        ),
    ]
