# Generated by Django 3.0.2 on 2020-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200802_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
