# Generated by Django 3.0.2 on 2020-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200802_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activityPeriod',
        ),
        migrations.AddField(
            model_name='user',
            name='activityPeriods',
            field=models.ManyToManyField(to='api.ActivityPeriod'),
        ),
    ]
