# Generated by Django 3.0.2 on 2020-08-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200802_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activityPeriods',
        ),
    ]
